[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["puppeteer-core", "@sparticuz/chromium"]

[functions."generate-quote-pdf"]
  timeout = 26
  memory = 1024

[[plugins]]
  package = "@netlify/plugin-nextjs"
